import './index.scss';
import '../../JS-components/libs.js';
import '../../blocks/navigation/navigation.js';
import '../../blocks/main-screen/main-screen.js';
import '../../blocks/preloader/preloader.js';
import '../../blocks/sending-form/sending-form.js';
import '../../blocks/carousel/carousel.js';
import '../../blocks/menu/menu.js';
import '../../blocks/picture-line/picture-line.js';